### ISSUE TITLE
error in the readme.me

### ISSUE THREAD

**Issue by Yusuf007R** [prabirshrestha/dwm-win32#26]
in the readme file it says the hotkey for togglebar is "mod+b' but in the config file is "mod+mod_control+b"
so if you press alt+b it doesn't work.
`{ MODKEY|MOD_CONTROL,           'B',       togglebar,           {0} },`

**Comment by prabirshrestha** [comment]
Feel free to send a PR.

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/dwm-win32/pull/27#issuecomment-695355498

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/dwm-win32/pull/27#issuecomment-695355498
