### ISSUE TITLE
Dependency on debug version of library VCRUNTIME140D.dll

### ISSUE THREAD

**Issue by ciwchris** [prabirshrestha/dwm-win32#35]
When I try to run the application I receive the error:

> The code execution cannot proceed because VCRUNTIME140D.dll was not found. Reinstalling the program may fix this problem.

Apparently the ['D' suffix implies a debug version of a library is being referenced](https://stackoverflow.com/questions/51437963/msvcp140d-dll-missing-is-there-a-way-around/51438071#51438071). Referencing the release version will make the application more accessible to others.

**Comment by vellankiindeevar** [comment]
ya even i am getting the same error

**Comment by ZigZag35** [comment]
downloading the .dll file from here: https://www.dllme.com/dll/files/vcruntime140d_dll.html
and pasting it to both C:\Windows\System32 and C:\Windows\SysWOW64 worked for me

**Comment by prabirshrestha** [comment]
Please try the latest release which should now be using the release build.

https://github.com/prabirshrestha/dwm-win32/releases/tag/v0.0.17
