### ISSUE TITLE
dwm failed to start (0xc000007b)

### ISSUE THREAD

**Issue by ZigZag35** [prabirshrestha/dwm-win32#36]
### Windows Version
windows 10 64-bit. 
### dwm version 
v0.0.16 (latest)

after installing the missing .dll files _(ucrtbased.dll and vcruntime140d.dll)_ to both C:\Windows\System32 and C:\Windows\SysWOW64,
running dwm outputs:

![image](https://user-images.githubusercontent.com/67876743/140897017-dd327025-6228-49c0-a04b-7ecd9bd47404.png)
[ the application failed to start correctly (0xc000007b). click on OK to close it. ]
reinstalling .NET35 and enabling didn't fix the issue.

**Comment by prabirshrestha** [comment]
Please try the latest release which should now be using the release build.

https://github.com/prabirshrestha/dwm-win32/releases/tag/v0.0.17
