### ISSUE TITLE
 auto hide/show the bar when a window goes fullscreen

### ISSUE THREAD

**Issue by amrbashir** [prabirshrestha/dwm-win32#43]
Awesome project, I am glad I found it. 

One thing that bother me is going into fullscreen for a video doesn't hide the bar which is kinda annoying since I have to manually hide/show it using the shortcut every time.

**Comment by prabirshrestha** [comment]
This is a great idea. I have needed to do the same for powerpoint slides. Need to figure out the win32 apis for this first.

**Comment by amrbashir** [comment]
When a windows goes into borderless fullscreen (like when you fullscreen a video in chrome), it simply calls `SetWindowPos()` with the current monitor size, followed by `ITaskbarList2::MarkFullscreenWindow` so the shell would hide the taskbar when this window is active. At least that's how chromium does it. (https://github.com/chromium/chromium/blob/f18e79d901f56154f80eea1e2218544285e62623/ui/views/win/fullscreen_handler.cc)

**Comment by amrbashir** [comment]
Seems like the only way (at least the one I could find) is to detect fullscreen by polling, something like how TaskbarX project detects it here https://github.com/ChrisAnd1998/TaskbarX/blob/57a9b5357fa517286e5b11a546dc86f75524a0fc/TaskbarX/TaskbarX/TaskbarCenter.vb#L408-L420

**Comment by amrbashir** [comment]
Closing as I think this project seems a bit unmaintained and I'd advise anyone to use https://github.com/LGUG2Z/komorebi since it works with the native windows taskbar pretty well and won't run in this issue which is quite hard to fix anyways.
