### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by amrbashir** [prabirshrestha/dwm-win32#44]
I can't seem to find any config related docs or if the app even have a config file. 
It would be nice to have a config file where one can change:
- keybindings
- exclude windows from tiling (useful to exclude apps like https://github.com/oliverschwendener/ueli)
- gap and margins
- bar position
- bar color

I listed them from high to low in terms of priority.

**Comment by prabirshrestha** [comment]
Config file can be found at https://github.com/prabirshrestha/dwm-win32/blob/master/config.h.in You need to manually compile it. Instructions can be found at https://github.com/prabirshrestha/dwm-win32#compiling. Ideally we could have a github actions that allows to build and upload the assets so you don't need to setup the environment.

If you provide the alt+i output, I can exclude `ueli` window and set it to floating or you can add your custom rule and compile.

**Comment by amrbashir** [comment]
> Config file can be found at [`master`/config.h.in](https://github.com/prabirshrestha/dwm-win32/blob/master/config.h.in?rgh-link-date=2021-12-08T00%3A58%3A21Z) You need to manually compile it.

That's what I was afraid of, so dwm-win32 inherited this from original dwm which is understandable.

> Ideally we could have a github actions that allows to build and upload the assets so you don't need to setup the environment.

yeah that can ease the pain a bit.

> If you provide the alt+i output, I can exclude ueli window and set it to floating or you can add your custom rule and compile.

It is just another electron app like vscode so the class is `Chrome_WidgetWin_1` and title is `ueli`

Thanks for the quick answer, I will close this since most of the things I mentioned already exits.
