### ISSUE TITLE
Pertag patch

### ISSUE THREAD

**Issue by adham-elaraby** [prabirshrestha/dwm-win32#51]
Would be great if the pertag patch can be implemented, this would allow tags to be set at different layouts at the same time.

Ie. Tag 1. Tiles and Tag 2. Monocle

**Comment by Ruberald** [comment]
@adhamramy just wondering if you got around to adding pertag. I checked your personal fork but it doesn't seem to have any such commits.

**Comment by adhamramy** [comment]
> @adhamramy just wondering if you got around to adding pertag. I checked your personal fork but it doesn't seem to have any such commits.

I have unfortunately not implemented it, due to a lack of time, and C knowledge, however, I'll try to make time in the coming month.

**Comment by Ruberald** [comment]
@adhamramy made a PR with the patch updated. Seems to work for me.

**Comment by adhamramy** [comment]
I've been testing it, and it seems to work without any issues till now on my system.
